#!/bin/bash

# Emphasize color codes

BOLD="\033[1m"

# Police color codes

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"

# Reset color code

RESET="\033[0m"

# redundant echoes

ERROR="\n"$RESET$BOLD$RED"Error or Quit... Press \"Enter\" to continue :"$RESET" "
SUCCESS="\n"$RESET$GREEN"SUCCESS"$RESET""
INVALID= ""$RESET$BOLD$RED"$SELECTED_OPTION is not a valid option. Please try again"$RESET""

while :
do
	clear
	echo -e ""$BOLD$BLUE"-----------------------------------------------"
	echo -e "|                                             |"
	echo -e "|                 "$RESET$GREEN"Main script"$RESET$BOLD$BLUE"                 |"
	echo -e "|    "$GREEN"(Select an option in the list bellow)"$BLUE"    |"
	echo -e "|                                             |" 
	echo -e "|---------------------------------------------|"
	echo -e "|                                             |"
	echo -e "|   "$RESET$BOLD"1.Preset-packages    4.Update-packages    "$BLUE"|"
	echo -e "|                                             |"
	echo -e "|   "$RESET$BOLD"2.Upgrade-packages   5.Install-packages   "$BLUE"|"
	echo -e "|                                             |"
	echo -e "|   "$RESET$BOLD"3.Fast-git-push      6.Quit               "$BLUE"|"
	echo -e "|                                             |"
	echo -e "-----------------------------------------------"$RESET""
	read SELECTED_OPTION
	case $SELECTED_OPTION in
		1)
			echo -ne ""$BOLD$YELLOW"These packages will be installed :\n"$RESET$BOLD"- vim\n- gcc\n- make\n- git\n- gpm\n"$RESET$BOLD$YELLOW"Do you want to continue ? [y/n] : "
			read CHOICE
			if [ $CHOICE == "y" ]; then
				sudo apt-get install vim gcc make git
				echo -e "$SUCCESS"; sleep 3
			else
				echo -ne "$ERROR"
				read INPUT
			fi;;
		2)
			echo -ne ""$BOLD$YELLOW"An upgrade will be performed on all installed packages\nDo you want to continue ? [y/n] : "
			read CHOICE
			if [ $CHOICE == "y" ]; then
				sudo apt-get upgrade
				echo -e "$SUCCESS"; sleep 3
			else
				echo -ne "$ERROR"
				read INPUT
			fi;;
		3)
			echo -ne ""$BOLD$YELLOW"All files will be added to git\nDo you want to continue ? [y/n] : "
			read CHOICE
			if [ $CHOICE == "y" ]; then
				echo -n "Give a correct path from home to the target git repository : "
				read GITREP
				cd ~/"$GITREP"; git add --all; git status
				echo -n "Enter a commit message : "
				read COMMIT_MESSAGE
				git commit -m "$COMMIT_MESSAGE"; git push
				echo -e "$SUCCESS"; sleep 3
			else
				echo -ne "$ERROR"
				read INPUT
			fi;;
		4)
			echo -ne ""$BOLD$YELLOW"An update on all installed packages will be performed\nDo you want to continue ? [y/n] : "
			read CHOICE
			if [ $CHOICE == "y" ]; then
				sudo apt-get update
				echo -e "$SUCCESS"; sleep 3
			else
				echo -ne "$ERROR"
				read INPUT
			fi;;
		5)
			echo -ne ""$BOLD$YELLOW"Which package(s) do you want to install : "
			read PACKAGES
			if [ -n "$PACKAGES" ]; then
				echo -ne "The following package(s) will be installed : $PACKAGES\nDo you want to continue ? [y/n] : "
				read CHOICE
				if [ $CHOICE == "y" ]; then
					sudo apt-get install $PACKAGES
					echo -e "$SUCESS"; sleep 3
				else
					echo -ne "$ERROR"
					read INPUT
				fi
			else
				echo -ne "$ERROR"
				read INPUT
			fi;;
		6)
			break;;
		*)
			echo -e "$INVALID"
			sleep 3;;
	esac
done
clear; echo "Goodbye"; sleep 0.5; clear
